### ISSUE TITLE
Publish agent jar as snapshot

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/elastic-otel-java#13]
```[tasklist]
### Tasks
- [x] add github action workflow
- [x] add buildkite pipeline
- [x] add shell script to execute the "build and publish snapshot" command (with no-op cmd)
- [x] create vault credentials for repository #66
- [x] validate workflow by running it manually
- [x] make gradle sign the artifacts with gpg
- [x] make gradle publish snapshot artifacts to a maven repository
- [x] final: make it publish to the staging repository for maven central publication
```
