### ISSUE TITLE
Capture span stack trace when the span ends

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/elastic-otel-java#16]
Allows to make our otel agent capture span stack traces, this requires:
- [x] define a shared vendor span attribute to store the stack trace and the storage format (text), spec in apm repo https://github.com/elastic/apm/pull/828
- [x] ~~define if any filtering is applied on stack trace (for example to remove agent/otel internals from it)~~ no as we plan to store it as-is on backend side, just make the UI reuse it as-is.
- [x] capture the stack trace when the span ends with a span processor, #21 
- [x] ~~use an ingest-pipeline to draft an apm-server solution, ideally that would allow to reuse the UI without further changes.~~ we decided it wasn't required and could be skipped.
- [x] make apm-server handle this span attribute and store the stack trace in the expected location (or just leave it as an ordinary otel attribute) https://github.com/elastic/apm-data/issues/177
- [x] make the UI compatible with the new span attribute, or make sure the feature is not disabled explicitly for Otel agents: https://github.com/elastic/kibana/issues/169769
- [x] ~~decide if we need to implement `span_stack_trace_min_duration` configuration option~~ postponed to #22
