### ISSUE TITLE
[META] Config: Tasks to reach agent config parity

### ISSUE THREAD

**Issue by jackshirazi** [elastic/elastic-otel-java#33]
```[tasklist]
### Tasks
- [ ] https://github.com/elastic/elastic-otel-java/issues/34
- [ ] https://github.com/elastic/elastic-otel-java/issues/35
- [ ] https://github.com/elastic/elastic-otel-java/issues/36
- [ ] https://github.com/elastic/elastic-otel-java/issues/37
- [ ] https://github.com/elastic/elastic-otel-java/issues/38
- [ ] Config: Implement remaining unimplemented options (needs multiple phases as there are over 100 options)
- [ ] https://github.com/elastic/elastic-otel-java/issues/42
- [ ] https://github.com/elastic/elastic-otel-java/issues/39
- [ ] https://github.com/elastic/elastic-otel-java/issues/40
```

**Comment by jackshirazi** [comment]
Closing this, next steps covered in https://github.com/elastic/elastic-otel-java/issues/300
